name: $(Build.SourceBranchName) - $(Build.RequestedFor) - $(date:yyyyMMdd)$(rev:.r)

trigger: none

parameters: 
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - prd

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: azureServiceConnection
    value: 'CITI-IAC-TF'
  - name: workingDirectory
    value: '$(Build.SourcesDirectory)'

stages:
################################################################################
# 1. PLAN STAGE
################################################################################
- stage: Plan
  displayName: 'Plan Infrastructure'
  jobs:
  - job: Terraform_Plan
    displayName: 'Terraform Plan'
    steps:
      # By default, the pipeline checks out the repo here
      - template: templates/terraform-init.yml
        parameters:
          azureServiceConnection: $(azureServiceConnection)
          workingDirectory: $(workingDirectory)
          TF_STATE_ACCESS_KEY: $(TF_STATE_ACCESS_KEY)

      - template: templates/terraform-plan-apply.yml
        parameters:
          azureServiceConnection: $(azureServiceConnection)
          workingDirectory: $(workingDirectory)
          tfvarsFile: ${{ parameters.environment }}.tfvars
      
      - script: |
          echo "Removing any .terraform directories"
          find $(Build.SourcesDirectory) -type d -name ".terraform" -exec rm -rf {} +
          find $(Build.SourcesDirectory) -type f -name ".terraform.local.hcl" -exec rm -f {} +
        displayName: 'Clean up .terraform  directories and hcl file'

      # Publish the entire repo as an artifact named "tf-files"
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Terraform Files'
        inputs:
          targetPath: '$(Build.SourcesDirectory)'
          artifact: 'tf-files'

################################################################################
# 2. DEPLOY STAGE
################################################################################
- stage: Deploy
  displayName: 'Deploy Infrastructure'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Terraform_Deploy
    displayName: 'Terraform Deploy'
    environment: 'DeployInfra'  # Environment with manual approval checks
    # Disable default checkout so we rely on the artifact instead
    strategy:
      runOnce:
        deploy:
          steps:
            # Disable default checkout
            - checkout: none 

            # Download the tf-files artifact published in the Plan stage
            - task: DownloadPipelineArtifact@2
              displayName: 'Download Terraform Files'
              inputs:
                artifact: 'tf-files'
                path: '$(Build.SourcesDirectory)'

            - template: templates/terraform-init.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                workingDirectory: $(workingDirectory)
                TF_STATE_ACCESS_KEY: $(TF_STATE_ACCESS_KEY)

            # If you want to re-plan in Deploy, do it here:
            - template: templates/terraform-plan-apply.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                workingDirectory: $(workingDirectory)
                tfvarsFile: ${{ parameters.environment }}.tfvars

            - template: templates/terraform-apply.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                workingDirectory: $(workingDirectory)

################################################################################
# 3. DESTROY STAGE
################################################################################
- stage: Destroy
  displayName: 'Destroy Infrastructure'
  dependsOn: Deploy
  condition: succeeded()  # or run this manually if desired
  jobs:
  - job: Terraform_Destroy
    displayName: 'Terraform Destroy'
    steps:
      # Disable default checkout
      - checkout: none 

      # Download the same tf-files artifact from the Plan stage
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Terraform Files'
        inputs:
          artifact: 'tf-files'
          path: '$(Build.SourcesDirectory)'

      - template: templates/terraform-init.yml
        parameters:
          azureServiceConnection: $(azureServiceConnection)
          workingDirectory: $(workingDirectory)
          TF_STATE_ACCESS_KEY: $(TF_STATE_ACCESS_KEY)

      - template: templates/terraform-plan-destroy.yml
        parameters:
          azureServiceConnection: $(azureServiceConnection)
          workingDirectory: $(workingDirectory)
          tfvarsFile: ${{ parameters.environment }}.tfvars

      - template: templates/terraform-destroy.yml
        parameters:
          azureServiceConnection: $(azureServiceConnection)
          workingDirectory: $(workingDirectory)
